### ISSUE TITLE
Some flaws yet Amazing

### ISSUE THREAD

**Issue by Ashfmate** [Hetari/Hebara-Language#2]
# Start
Your project is great and I really like your idea of making the operators in a string

I do have to say that since you are using python, some things will be made easier and some made harder

## Easy
String manipulation, splitting and the list goes on, you can implement a way to read the file very effectively (not efficient)

## Hard
Lack of a struct to define non-terminal expressions, slow and python does not natively support enums (I know you can import enum but it is not native)

# Conclusion
In the end I applaud you and believe you can make an amazing language knowing you personally, one thing that you can use is a CLI tool, once you have a good foundation for your language then you can invest in a good CLI tool or maybe if you are daring enough, make the language accessible through a GUI application

**Comment by hetari** [comment]
Still in process, thanks for sharing.
